-- MySQL Workbench Synchronization
-- Generated: 2019-05-21 12:01
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: sna.17

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER SCHEMA `inekit1`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

CREATE TABLE IF NOT EXISTS `inekit1`.`Employees` (
  `emp_ID` INT(11) NOT NULL,
  `Initials` VARCHAR(45) NULL DEFAULT NULL,
  `Post` VARCHAR(45) NULL DEFAULT NULL,
  `Passport` INT(45) NULL DEFAULT NULL,
  `Home_adress` MEDIUMTEXT NULL DEFAULT NULL,
  `Home_phone` INT(11) NULL DEFAULT NULL,
  `Mobile_phone` INT(11) NULL DEFAULT NULL,
  `Perf` VARCHAR(45) NULL DEFAULT NULL,
  `Role` VARCHAR(45) NULL DEFAULT NULL,
  `Date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`emp_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `inekit1`.`Shedle` (
  `Perf_ID` INT(11) NOT NULL,
  `Perf_name` VARCHAR(45) NULL DEFAULT NULL,
  `Datetime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Perf_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `inekit1`.`Performances` (
  `ID` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Author` VARCHAR(45) NULL DEFAULT NULL,
  `Cr_year` VARCHAR(45) NULL DEFAULT NULL,
  `Actors_ID` INT(11) NOT NULL,
  `Actor` VARCHAR(45) NULL DEFAULT NULL,
  `Gerne` VARCHAR(45) NULL DEFAULT NULL,
  `Acts_number` INT(11) NULL DEFAULT NULL,
  `Plot` LONGTEXT NULL DEFAULT NULL,
  `Stuff_ID` INT(11) NULL DEFAULT NULL,
  `Stuff` VARCHAR(45) NULL DEFAULT NULL,
  `Price` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Actors_ID`, `ID`),
  INDEX `fk_Employees_has_Shedle_Shedle1_idx` (`ID` ASC) ,
  INDEX `fk_Employees_has_Shedle_Employees_idx` (`Actors_ID` ASC) ,
  CONSTRAINT `fk_Employees_has_Shedle_Employees`
    FOREIGN KEY (`Actors_ID`)
    REFERENCES `inekit1`.`Employees` (`emp_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_has_Shedle_Shedle1`
    FOREIGN KEY (`ID`)
    REFERENCES `inekit1`.`Shedle` (`Perf_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
