-- MySQL Workbench Synchronization
-- Generated: 2019-05-26 17:27
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: RABOTA

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `mydv` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `mydv`.`Employees` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Initials` VARCHAR(45) NULL DEFAULT NULL,
  `post` VARCHAR(45) NULL DEFAULT NULL,
  `passport` VARCHAR(45) NULL DEFAULT NULL,
  `home_adress` VARCHAR(45) NULL DEFAULT NULL,
  `h_phone` VARCHAR(45) NULL DEFAULT NULL,
  `m_phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydv`.`Performanes` (
  `id` INT(11) NOT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Pr_year` INT(11) NULL DEFAULT NULL,
  `Author` VARCHAR(45) NULL DEFAULT NULL,
  `Gerne` VARCHAR(45) NULL DEFAULT NULL,
  `Acts_number` INT(11) NULL DEFAULT NULL,
  `Plot` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydv`.`Actors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Emp_id` INT(11) NOT NULL,
  `Perf_id` INT(11) NOT NULL,
  `Role` VARCHAR(45) NULL DEFAULT NULL,
  `Perf_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Actors_Employees1_idx` (`Emp_id` ASC) ,
  INDEX `fk_AcSh_Performanes1_idx` (`Perf_id` ASC) ,
  CONSTRAINT `fk_Actors_Employees1`
    FOREIGN KEY (`Emp_id`)
    REFERENCES `mydv`.`Employees` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_AcSh_Performanes1`
    FOREIGN KEY (`Perf_id`)
    REFERENCES `mydv`.`Performanes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydv`.`Inventary` (
  `Inv_nmbr` INT(11) NOT NULL AUTO_INCREMENT,
  `Type` VARCHAR(45) NULL DEFAULT NULL,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Perf_id` INT(11) NOT NULL,
  PRIMARY KEY (`Inv_nmbr`),
  INDEX `fk_Inventary_Performanes1_idx` (`Perf_id` ASC) ,
  CONSTRAINT `fk_Inventary_Performanes1`
    FOREIGN KEY (`Perf_id`)
    REFERENCES `mydv`.`Performanes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydv`.`Shedle` (
  `id` INT(11) NOT NULL,
  `Perf_id` INT(11) NOT NULL,
  `price` INT(11) NULL DEFAULT NULL,
  `Perf_dtime` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Shedle_Performanes1_idx` (`Perf_id` ASC) ,
  CONSTRAINT `fk_Shedle_Performanes1`
    FOREIGN KEY (`Perf_id`)
    REFERENCES `mydv`.`Performanes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
